name: Análisis de Calidad con SonarQube

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonarcloud:
    name: Análisis SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Construir y analizar con Maven y SonarCloud
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=juandmaes1_DYAS-Construccion-de-Software -Dsonar.organization=juandmaes1 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=4201c7b11d4331266bdf7fe6f30f1c8cc0e93851
